import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>This is Navbar</h1>
        <div className="flex gap-5">
          <div>
            <h1>sidebar</h1>
          </div>
          <div>{children}</div>
        </div>
        <h1>This is Footer</h1>
      </body>
    </html>
  );
}
